<?php
    namespace App\Http\Utilities;

    class City{
        protected static $city=  [
            'Hà Nội'=>'HANOI'  ,
            'Hồ Chí Minh' => 'HOCHIMINH',
            'Hải Phòng' => 'HAIPHONG',
            'Đà Nẵng'=> 'DANANG' ,
            'Hà Giang' => 'HAGIANG',
            'Cao Bằng' => 'CAOBANG',
             'Lai Châu' =>'LAICHAU',
            'Lào Cai' =>'LAOCAI' ,
            'Tuyên Quang' =>'TUYENQUANG' ,
            'Lạng Sơn' =>'LANGSON' ,
            'Bắc Kạn' =>'BACKAN' ,
            'Thái Nguyên'=> 'THAINGUYEN' ,
            'Yên Bái'=>'YENBAI'  ,
            'Sơn La' =>'SONLA',
            'Phú Thọ' => 'PHUTHO',
            'Vĩnh Phúc'=> 'VINHPHUC' ,
            'Quảng Ninh' => 'QUANGNINH',
            'Bắc Giang' => 'BACGIANG',
            'Bắc Ninh' => 'BACNINH',
            'Hải Dương' =>'HAIDUONG' ,
            'Hưng Yên' => 'HUNGYEN',
            'Hòa Bình' => 'HOABINH',
            'Hà Nam' => 'HANAM',
            'Nam Định' => 'NAMDINH',
            'Thái Bình' =>'THAIBINH' ,
             'Ninh Bình' =>'NINHBINH',
            'Thanh Hóa' => 'THANHHOA',
            'Nghệ An' => 'NGHEAN',
             'Hà Tĩnh'=>'HATINH' ,
            'Quảng Bình' =>'QUANGBINH' ,
            'Quảng Trị' => 'QUANGTRI',
            'Thừa Thiên Huế' =>'THUATHIENHUE' ,
            'Quảng Nam'=> 'QUANGNAM' ,
            'Quảng Ngãi' => 'QUANGNGAI',
            'Kon Tum' => 'KONTUM',
            'Bình Định'=> 'BINHDINH' ,
            'Gia Lai' =>'GIALAI' ,
             'Phú Yên' =>'PHUYEN',
            'Đăk Lăk' =>'DAKLAK',
            'Khánh Hòa' =>'KHANHHOA' ,
            'Lâm Đồng' => 'LAMDONG',
             'Bình Phước' => 'BINHPHUOC',
            'Bình Dương' => 'BINHDUONG',
            'Ninh Thuận' => 'NINHTHUAN',
            'Tây Ninh' => 'TAYNINH',
            'Bình Thuận' => 'BINHTHUAN',
            'Đồng Nai' =>'DONGNAI' ,
            'Long An' => 'LONGAN',
            'Đồng Tháp'=> 'DONGTHAP' ,
            'An Giang' =>'ANGIANG' ,
            'Bà Rịa Vũng Tàu' =>'BARIAVUNGTAU' ,
            'Tiền Giang' => 'TIENGIANG',
             'Kiên Giang' =>'KIENGIANG',
            'Trà Vinh' =>'TRAVINH' ,
            'Bến Tre' => 'BENTRE',
            'Vĩnh Long' => 'VINHLONG',
            'Sóc Trăng' => 'SOCTRANG',
            'Bạc Liêu' => 'BACLIEU',
            'Cà Mau' => 'CAMAU',
             'Điện Biên'=> 'DIENBIEN',
           'Đắk Nông'  => 'DAKNONG',
            'Hậu Giang'  =>  'HAUGIANG'
        ];
        public static function all(){
            return array_keys(static::$city);
        }
    }